name: vacationzoom.com
favicon: null
layout_spectrum: 0.7429183141794056
typography_spectrum: 0.6534434182103723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7705393529031426
  lightness: 0.9858572254888713
  saturation: 0.17948183324187994
  rhythmicContrast: 0.1852352588903159
purpose: []
