name: vacationzoom.com
favicon: null
layout_spectrum: 0.7429183141794056
typography_spectrum: 0.6534434182103723
title: 'Disney Cruises, Hawaii Vacations, Mexico Vacations'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c151b'
    - '#f3eceb'
    - '#1f71a1'
    - '#c32e1f'
    - '#c6810a'
  brandStrength: 0.7705393529031426
  lightness: 0.9858572254888713
  saturation: 0.17948183324187994
  rhythmicContrast: 0.1852352588903159
purpose: []
